export const DUMMY_REPOSITORIES = [
  {
    id: "1",
    name: "gitpulse",
    description: "Platform analisis kontribusi GitHub menggunakan Machine Learning",
    language: "TypeScript",
    visibility: "private",
    stars: 12,
    forks: 3,
    updatedAt: "2 hari lalu",
    productivityState: "active",
    healthScore: 87,
    healthGrade: "B",
    status: "active",
    breakdown: {
      dokumentasi: 18,
      issueManagement: 14,
      commitQuality: 20,
      konsistensi: 18,
      kolaborasi: 10,
      recency: 7,
    },
    recommendations: [
      "Tingkatkan frekuensi penutupan issue",
      "Gunakan conventional commits",
    ],
  },
  {
    id: "2",
    name: "ml-service",
    description: "FastAPI service untuk model Machine Learning GitPulse",
    language: "Python",
    visibility: "private",
    stars: 5,
    forks: 1,
    updatedAt: "5 hari lalu",
    productivityState: "moderate",
    healthScore: 72,
    healthGrade: "C",
    status: "active",
    breakdown: {
      dokumentasi: 14,
      issueManagement: 12,
      commitQuality: 18,
      konsistensi: 14,
      kolaborasi: 8,
      recency: 6,
    },
    recommendations: [
      "Tambahkan README yang lebih lengkap",
      "Tingkatkan konsistensi commit",
    ],
  },
  {
    id: "3",
    name: "portofolio-web",
    description: "Website portofolio pribadi",
    language: "JavaScript",
    visibility: "public",
    stars: 8,
    forks: 2,
    updatedAt: "1 bulan lalu",
    productivityState: "inactive",
    healthScore: 45,
    healthGrade: "D",
    status: "inactive",
    recommendations: [
      "Repo tidak aktif sejak lama",
      "Pertimbangkan untuk mengarsipkan",
    ],
    breakdown: {
      dokumentasi: 10,
      issueManagement: 8,
      commitQuality: 12,
      konsistensi: 6,
      kolaborasi: 5,
      recency: 4,
    },
  },
  {
    id: "4",
    name: "data-scraper",
    description: "Tool scraping data untuk kebutuhan penelitian",
    language: "Python",
    visibility: "private",
    stars: 2,
    forks: 0,
    updatedAt: "3 hari lalu",
    productivityState: "active",
    healthScore: 91,
    healthGrade: "A",
    status: "active",
    breakdown: {
      dokumentasi: 20,
      issueManagement: 18,
      commitQuality: 23,
      konsistensi: 18,
      kolaborasi: 7,
      recency: 5,
    },
    recommendations: [
      "Pertahankan kualitas commit yang baik",
    ],
  },
];