import { Team, TeamMember } from "../types";

export const DUMMY_TEAMS: Team[] = [
  {
    id:          "1",
    name:        "Proyek Tugas Akhir",
    description: "Tim pengerjaan Tugas Akhir Teknik Informatika 2026",
    repos:       ["gitpulse", "ml-service"],
    memberCount: 4,
    inviteCode:  "TA2026-ABC",
    createdAt:   "1 Januari 2026",
    myRole:      "owner",
  },
  {
    id:          "2",
    name:        "Tim Capstone 2026",
    description: "Kelompok capstone project semester 6",
    repos:       ["capstone-web"],
    memberCount: 6,
    inviteCode:  "CAP2026-XYZ",
    createdAt:   "15 Januari 2026",
    myRole:      "evaluator",
  },
  {
    id:          "3",
    name:        "Kelompok Praktikum",
    description: "Praktikum pemrograman web",
    repos:       ["praktikum-web"],
    memberCount: 3,
    inviteCode:  "PRAK-DEF",
    createdAt:   "20 Februari 2026",
    myRole:      "contributor",
  },
];

export const DUMMY_MEMBERS: TeamMember[] = [
  {
    id:                  "1",
    name:                "Dinda Atikah",
    username:            "dindaatikah",
    avatar:              "",
    role:                "owner",
    memberStatus:        "Active",
    commitVelocity:      18.4,
    contributionShare:   0.45,
    activityConsistency: 0.8,
    activeWeeksRatio:    0.9,
    recommendation:      "Kontribusimu sangat konsisten, pertahankan pola kerja ini!",
  },
  {
    id:                  "2",
    name:                "Latifa Salsabila",
    username:            "latifasalsabila",
    avatar:              "",
    role:                "evaluator",
    memberStatus:        "Active",
    commitVelocity:      12.1,
    contributionShare:   0.30,
    activityConsistency: 1.2,
    activeWeeksRatio:    0.85,
    recommendation:      "Tingkatkan konsistensi commit mingguan untuk hasil lebih optimal.",
  },
  {
    id:                  "3",
    name:                "Ahmad R.",
    username:            "ahmadr",
    avatar:              "",
    role:                "contributor",
    memberStatus:        "Passive",
    commitVelocity:      5.2,
    contributionShare:   0.15,
    activityConsistency: 2.4,
    activeWeeksRatio:    0.55,
    recommendation:      "Frekuensi commit masih rendah, coba tingkatkan aktivitas mingguan.",
  },
  {
    id:                  "4",
    name:                "Farah N.",
    username:            "farabn",
    avatar:              "",
    role:                "contributor",
    memberStatus:        "Inactive",
    commitVelocity:      1.1,
    contributionShare:   0.10,
    activityConsistency: 4.1,
    activeWeeksRatio:    0.25,
    recommendation:      "Aktivitas sangat rendah, segera tingkatkan kontribusi ke repository.",
  },
];